spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/gimnasio
spring.datasource.username=postgres
spring.datasource.password=101626

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true